//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int ID { get; set; }
        public Nullable<int> ID__Test { get; set; }
        public string Question1 { get; set; }
        public byte[] Photo { get; set; }
        public string Answer_One { get; set; }
        public string Answer_Two { get; set; }
        public string Answer_Three { get; set; }
        public string True_Answer { get; set; }
        public Nullable<bool> IsDone { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
